### ISSUE TITLE
sharing without Atmos?

### ISSUE THREAD

**Issue by tirelibirefe** [cloudposse/terraform-aws-components#1160]
### Describe the Feature

could you please share pure terraform code without Atmos config?

### Expected Behavior

because don't want to struggle with Atmos.

### Use Case

I don't need to Atmos.

### Describe Ideal Solution

pure consistent terraform code stack

### Alternatives Considered

terragrunt is useful too.

### Additional Context

good wishes.

**Comment by Nuru** [comment]
@tirelibirefe Would you please be more specific? What Atmos configuration are you referring to?

The components under `modules/` are the main thing we are sharing, and they do not have any Atmos configuration or dependencies.

**Comment by osterman** [comment]
@Nuru our markdown documentation of components uses stack configurations. I think @tirelibirefe is requesting we document them as strictly terraform root modules with variables.

**Comment by osterman** [comment]
@tirelibirefe, there are indeed many ways to use Terraform, and if Terragrunt works well for your team, that’s great!

Our components are part of Cloud Posse’s opinionated reference architecture for AWS, which you can find documented at [docs.cloudposse.com](https://docs.Cloudposse.com). While they rely on our Terraform module ecosystem, which is flexible enough to be used with Terragrunt, the documentation naturally leans toward how we implement things in our own projects.

We share these components with the community, hoping they’re helpful to others. Since this repo is how we provide reference architecture updates to our customers, the docs need to reflect our specific approach. As the saying goes, trying to please everyone can sometimes mean pleasing no one...
