### ISSUE TITLE
Providers file in modules

### ISSUE THREAD

**Issue by hristo-ganekov-sumup** [cloudposse/terraform-aws-components#332]
## Describe the Bug
https://github.com/cloudposse/terraform-aws-components/blob/master/modules/account/providers.tf is present in accounts module (and probably elsewhere).

This prevents the module to be invoked with providers block (containing variables, or in loop)

This is a bad practice as described but Hashicorp https://www.terraform.io/docs/language/modules/develop/providers.html

"A module intended to be called by one or more other modules must not
contain any provider blocks. A module containing its own provider configurations
is not compatible with the for_each, count, and depends_on arguments that were 
introduced in Terraform v0.13. For more information, see Legacy Shared Modules
with Provider Configurations." 

## Expected Behavior
To not have providers definition in module

## Steps to Reproduce
"""
provider "aws" {
  region = var.region
  access_key = var.aws_access_key_id
  secret_key = var.aws_secret_access_key
}

module "aws_accounts" {
  source = "github.com/cloudposse/terraform-aws-components.git//modules/account"
..
..
..
}
"""

**Comment by Gowiem** [comment]
@hristo-ganekov-sumup These module are not expected to be utilized as child modules in a root module like you're attempting. The point of calling these `components` is that they're **shareable root modules**. You can utilize a tool like [`vendir`](https://github.com/vmware-tanzu/carvel-vendir) to vendor them into your repository wholesale (or just copy them directly from source into your repository) and then utilize them as you would any other root module. 

So to be clear: This is expected functionality. We're not sharing regular child modules as part of this repository, but something more than that. 

Going to close this issue since it's just a bit of confusion, but please let me know if you have any other questions 👍
